FROM node:10 AS builder

# some bower components expect that bower is installed
RUN npm install -g bower

# working directory
RUN mkdir -p /project && \
    chown node /project
WORKDIR /project
USER node

# cache node_modules
COPY --chown=node yarn-offline-mirror /project/yarn-offline-mirror
COPY --chown=node .yarnrc package.json yarn.lock /project/
RUN yarn install --frozen-lockfile --non-interactive --no-progress && \
    yarn cache clean && \
    bower cache clean

# do the build
COPY --chown=node *.* /project/
COPY --chown=node karma /project/karma/
COPY --chown=node src /project/src/
RUN yarn run build

# ------------------------------------------------------------

FROM nginx:1.15-alpine

COPY --from=builder /project/bin/static /usr/share/nginx/html
