sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_script:
  # disable services enabled by default to avoid port conflicts
  - sudo service postgresql stop
  # load cached Docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

script:
  - ./ci-build.sh

before_cache:
  # cache Docker images
  - ./cache-builder-images.sh
  - mkdir -p $HOME/docker
  - docker save liipi-api-builder-cache | gzip -1 > "$HOME/docker/liipi-api-builder-cache.tar.gz"
  - docker save liipi-web-builder-cache | gzip -1 > "$HOME/docker/liipi-web-builder-cache.tar.gz"

cache:
  directories:
    - $HOME/docker

notifications:
  email: false
  flowdock:
    secure: h3OB+ZyOFh6m/43twXDTh15enuvALOVvCNe81+doFj5o0s9x+n1K06x02hU2ISkHt5MYGg5JNtyeDTg2DDDht3TsfJcM3U8P/auMaIB7jt6Cwwrp0WPbFwyMR5t+CHYK27teeaopPtXbk+PWdq7FMma1kzvgOZlC6yq6OOj4hwM=
