language: java
jdk:
  - oraclejdk8
env:
  - PTOR_DIR=$TRAVIS_BUILD_DIR/etc/protractor APP_MODULE=$TRAVIS_BUILD_DIR/application DISPLAY=:99 SPRING_PROFILES_ACTIVE=env_travis
addons:
  apt:
    packages:
      - language-pack-fi
  postgresql: "9.3"
sudo: false
cache:
  directories:
    - $HOME/.m2
    - etc/protractor/node_modules
    - application/src/main/frontend/node_modules/
    - application/src/main/frontend/node/
    - application/src/main/frontend/vendor/
before_install:
  - sh -e /etc/init.d/xvfb start
install:
  - bash etc/scripts/db/psql-init-db.sh -U postgres
  - cd $PTOR_DIR
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR
  - mvn verify -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn coveralls:report
notifications:
  email: false
  flowdock:
    secure: h3OB+ZyOFh6m/43twXDTh15enuvALOVvCNe81+doFj5o0s9x+n1K06x02hU2ISkHt5MYGg5JNtyeDTg2DDDht3TsfJcM3U8P/auMaIB7jt6Cwwrp0WPbFwyMR5t+CHYK27teeaopPtXbk+PWdq7FMma1kzvgOZlC6yq6OOj4hwM=
