language: java
jdk:
  - oraclejdk8
env:
  - PTOR_DIR=$TRAVIS_BUILD_DIR/etc/protractor APP_MODULE=$TRAVIS_BUILD_DIR/application SPRING_PROFILES_ACTIVES=env_travis DISPLAY=:99
before_install:
  - sh -e /etc/init.d/xvfb start
install:
  - mvn package -Dmaven.javadoc.skip=true -B -V
before_script:
  - cd $PTOR_DIR
  - npm install
  - bash protractor.sh start
  - bash protractor.sh wait_until_started
script:
  - bash protractor.sh test
  - bash protractor.sh verify
after_success:
  - cd $APP_MODULE && mvn clean test jacoco:report coveralls:report
notifications:
  flowdock:
    secure: h3OB+ZyOFh6m/43twXDTh15enuvALOVvCNe81+doFj5o0s9x+n1K06x02hU2ISkHt5MYGg5JNtyeDTg2DDDht3TsfJcM3U8P/auMaIB7jt6Cwwrp0WPbFwyMR5t+CHYK27teeaopPtXbk+PWdq7FMma1kzvgOZlC6yq6OOj4hwM=
