version: '2.2'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: liipi-api
    environment:
      PSQL_USERNAME: liipi
      PSQL_PASSWORD: liipi
      PSQL_HOST: db:5432
    mem_limit: 500m
    mem_reservation: 400m

  web:
    build:
      context: web
      dockerfile: Dockerfile-web
    image: liipi-web
    environment:
      API_URL: http://api:8080
    ports:
      - "8080:80"
    mem_limit: 50m
    mem_reservation: 20m

  db:
    build:
      context: db
      dockerfile: Dockerfile-db
    image: liipi-db
    environment:
      POSTGRES_USER: liipi
      POSTGRES_PASSWORD: liipi
    ports:
      - "5432:5432"
    mem_limit: 100m
    mem_reservation: 50m

  test:
    build:
      context: test
      dockerfile: Dockerfile-test
    image: liipi-test
    environment:
      BASEURL: http://web/
    mem_limit: 1200m
    mem_reservation: 1100m
