version: '3.6'
services:

  web:
    build:
      context: application/src/main/frontend
      dockerfile: Dockerfile-web
    image: liipi-web
    environment:
      API_URL: http://api:8080
    ports:
      - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: liipi-api

  test:
    build:
      context: etc/protractor
      dockerfile: Dockerfile-test
    image: liipi-test
    environment:
      BASEURL: http://web/
