version: '3.6'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: liipi-api

  web:
    build:
      context: web
      dockerfile: Dockerfile-web
    image: liipi-web
    environment:
      API_URL: http://api:8080
    ports:
      - "8080:80"

  test:
    build:
      context: test
      dockerfile: Dockerfile-test
    image: liipi-test
    environment:
      BASEURL: http://web/
