#!/bin/bash

function init() {
  export PGCLIENTENCODING="UTF8"
  : ${LIIPI_DB:="liipidb"}
  : ${LIIPI_SCHEMA:="liipi"}
  : ${LIIPI_USER:="liipi"}
  : ${LIIPI_PASS:="liipipw"}
}

function run() {
  psql -v ON_ERROR_STOP=1 "$@" <<EOF
DROP DATABASE IF EXISTS $LIIPI_DB;
DROP USER IF EXISTS $LIIPI_USER;

CREATE DATABASE $LIIPI_DB ENCODING 'UTF8' LC_COLLATE 'fi_FI.UTF-8' LC_CTYPE 'fi_FI.UTF-8' TEMPLATE template0;
CREATE USER $LIIPI_USER WITH PASSWORD '$PASS';
GRANT CONNECT, TEMP ON DATABASE $LIIPI_DB TO $LIIPI_USER;

\connect $LIIPI_DB

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;
CREATE SCHEMA $LIIPI_SCHEMA;

GRANT ALL PRIVILEGES ON SCHEMA $LIIPI_SCHEMA TO $LIIPI_USER;

\q
EOF
}

VERBOSE="true"
source $(dirname $0)/../main.inc

