package fi.hsl.parkandride.core.domain;

public enum Permission {
    ALL_OPERATORS,
    FACILITY_CREATE,
    FACILITY_UPDATE,
    OPERATOR_CREATE,
    OPERATOR_UPDATE,
    CONTACT_CREATE,
    CONTACT_UPDATE,
    USER_CREATE,
    USER_UPDATE,
    USER_VIEW,
    FACILITY_STATUS_UPDATE,
    HUB_CREATE,
    HUB_UPDATE
}
