@startuml

() HTTP
package "Primary Adapters" {
  package "Admin UI" {
    [Rest Controller] as AdminRestCtrl
  }

  package "Open API" {
    [Rest Controller] as OpenRestCtrl
  }

  package "Operator Push API" {
    [Rest Controller] as PushRestCtrl
  }
}
HTTP - AdminRestCtrl
HTTP - OpenRestCtrl
HTTP - PushRestCtrl

package "Core" {
  () "Application Service API" as IAS
  [Application Service] as AS

  package "Secondary Ports" {
    () "Repository API" as IR
    () "Messaging API" as IM
  }

  IAS - AS
  AS -> [Domain]
  AS -> IR
  AS -> IM
}

package "Secondary Adapters" {
  package "Main Data Storage" {
    IR - [Dao]
  }

  package "Email Service" {
    IM - [Store and Forward Proxy]
  }
}

AdminRestCtrl -> IAS
OpenRestCtrl -> IAS
PushRestCtrl -> IAS

@enduml