FROM dockerfile/java:oracle-java8
MAINTAINER HSLdevcom/parkandrideAPI "https://github.com/HSLdevcom/parkandrideAPI"
ENV REFRESHED_AT 2014-09-26

EXPOSE 8080
CMD java -jar /data/parkandride/parkandride-latest.jar