= HSL Park and Ride Documentation
:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs


[[overview]]
== Overview

Park and Ride is one of the solutions to tackle Helsinki regions growing population and traffic
by encouraging citizens to leave their cars outside of the most congested areas and continuing
their trip with public transportation. HSL Park and Ride application contains all the important
information about parking facilities and their services near public transportation hubs. The
application is used by HSL, parking operators, roadside displays and third party applications.
All data is provided free of charge under the link:http://creativecommons.org/licenses/by/4.0/[CC BY 4.0 license].

API follows REST conventions roughly. Resources are divided into collection and item URLs.
Collection resources typically accept GET-parameters for filtering, paging and sorting items.
Reading data uses GET-method and doesn't require authorization - except for user management.
Restricted modifications use either POST on collection-URL for creating new items and PUT
on item URL for updates.

DELETE is not directly supported currently but the goal is achieved using e.g. a status field.
However, if sometime in the future we need to delete something for reason or another,
*please prepare for 404 on a resource that has previously returned a result*.

Somewhat contrary to strict REST ideology we provide all dependent (deep) information directly from
item URLs. You need not get basic relations using nested calls.
Shared resources are referenced using IDs (not URIs), and until HATEOAS-type links are implemented
one needs to know and construct URIs using templates in order get details of such shared resources
(e.g. operator or contacts).
For most cases there exists an ID-based filtering parameter (`ids`) for collection URLs
that allow getting basic information of all referred resources with single request.

=== Changes to the API

We aim to develop the API in a backwards compatible manner, i.e. features are only added while
maintaining old semantics. However, we appreciate your feedback and will take it into account
in future development. In the end, this may lead to a need to refactor the APIs.
Unless such a breaking change is due to some critical security related issue, we will give you
a warning about it well in advance.
_Upcoming: Please register yourself and your app to a mailing list
in order to receive announcements of coming changes. For now, you can contact petro.tamminen@hsl.fi._

=== Development

Park and Ride application is developed as an Open Source project in GitHub:
https://github.com/HSLdevcom/parkandrideAPI.

Please, report bugs and feature requests as GitHub issues.

=== Overview of the Data Model

link:../assets/datamodel.png[UML diagram of the HSL Park and Ride data model]

=== Examples

Most API-features are used by the link:https://p.hsl.fi/[Park and Ride maintenance UI] and
link:https://github.com/HSLdevcom/parkandrideAPI/tree/master/application/src/main/frontend/src[its source code]
contains real life example.

Upcoming features can be tested in https://test.p.hsl.fi

=== License

Source code is licensed under AGPL and EUPL licenses. For details, see
https://github.com/HSLdevcom/parkandrideAPI#license.

== General Features

[[authentication]]
=== Authentication

Mutable operations require authentication using the `Authorization` header as shown in the following example.
The value is the string `Bearer` followed by the API user's token. Operators can create API users and tokens for them through the link:/#/users[user administration page].

include::{generated}/authentication-example/http-request.adoc[]

NOTE: Authentication is *not* needed for read-only (GET) methods.


[[usage-tracking]]
=== Usage tracking
API usage is tracked by logging all incoming requests per application. To enable tracking for your specific application's
needs, please include the `Liipi-Application-Id` header in your requests. The header values must match the following
pattern: `[a-zA-Z0-9_\-\./]{3,20}`. If no header is specified, the request will still be logged with `null` apllication id.
The web user interface uses `liipi-ui` as its identifier.

include::{generated}/usage-tracking-example/http-request.adoc[]

[[formats]]
=== Supported Formats

Both JSON and http://geojson.org[GeoJSON] (Feature/FeatureCollection) are supported for facilities and hubs.
In JSON format locations are provided using GeoJSON Geometries (Point or Polygon).
GeoJSON's feature centric view contains only basic metadata of given entity.

Required format is specified either with `.json` or `.geojson` suffix or by using `Accept` header with
`application/json` or `application/vnd.geo+json` value.

include::{generated}/json-suffix-example/curl-request.adoc[]

include::{generated}/geojson-suffix-example/curl-request.adoc[]

include::{generated}/json-header-example/curl-request.adoc[]

include::{generated}/geojson-header-example/curl-request.adoc[]

If no suffix or `Accept` header is given, JSON is used by default.

include::{generated}/json-default-example/curl-request.adoc[]


[[searching]]
=== General Search Features

While simple listings (e.g. enums) may return arrays of values directly, searches return results
that are wrapped within an object. This result object has boolean field `hasMore` that indicates whether
or not there's more result rows available:

[source,json]
----
{
  "results": [...]
  "hasMore": false
}
----

Limiting result size is done via `limit` and `offset` int-parameters.
Limit defines the maximum number of items to be returned and offset the zero-based index of
the first row to be returned. Use negative value for `limit` to get all the results.

Ordering of result items is done via `sort.by` and `sort.dir` parameters.
Allowed values of `sort.by` is resource dependent but typically
at least `name.fi`, `name.sv` and `name.en` are supported.
Direction is given as `ASC` or `DESC`.

include::{generated}/limit-offset-sort-example/curl-request.adoc[]


[[localization]]
=== Localization

Park and Ride data is localized in Finnish, Swedish and English.
Localized fields are represented as objects with `fi`, `sv` and `en` fields:

[source,json]
----
{
  "name": {
    "fi": "Nimi",
    "sv": "Namn",
    "en": "Name"
  }
}
----

Optional localized fields are either `null` or localized for all supported languages.
For example missing (optional) info:

[source,json]
----
{
  "info": null
}
----

WARNING: None of the textual fields may contain HTML-markup, and *must be escaped before rendering*.

[[enumerations]]
=== Enumerations

Park and Ride utilizes enumerated values for much of it's metadata. Current value-sets are available via REST.

Capacity type defines different kind of parking slot types:

include::{generated}/enumeration-capacity-types-example/http-request.adoc[]
include::{generated}/enumeration-capacity-types-example/http-response.adoc[]

Usage specifies the purpose of the capacity. See <<capacity,Capacity>>.

include::{generated}/enumeration-usages-example/http-request.adoc[]
include::{generated}/enumeration-usages-example/http-response.adoc[]

Day type is a rough categorization of day types with different opening hours and/or pricing:

include::{generated}/enumeration-day-types-example/http-request.adoc[]
include::{generated}/enumeration-day-types-example/http-response.adoc[]

Services provided by a facility:

include::{generated}/enumeration-services-example/http-request.adoc[]
include::{generated}/enumeration-services-example/http-response.adoc[]

Payment methods accepted by a facility:

include::{generated}/enumeration-payment-methods-example/http-request.adoc[]
include::{generated}/enumeration-payment-methods-example/http-response.adoc[]

Facility status indicates whether the facility is operating normally or is exceptionally closed. See <<status,Status>>.

include::{generated}/enumeration-facility-statuses-example/http-request.adoc[]
include::{generated}/enumeration-facility-statuses-example/http-response.adoc[]

Pricing method is a shortcut for maintaining actual facility pricing information:

include::{generated}/enumeration-pricing-methods-example/http-request.adoc[]
include::{generated}/enumeration-pricing-methods-example/http-response.adoc[]


[[operators]]
== Operators

All facilities are operated by an operator. Operator can be listed with:

include::{generated}/all-operators-example/http-request.adoc[]
include::{generated}/all-operators-example/http-response.adoc[]

Details of an operator can be fetched with:

include::{generated}/operator-details-example/http-request.adoc[]
include::{generated}/operator-details-example/http-response.adoc[]

=== Summary of Operator Model

include::{generated}/operator-details-example/response-fields.adoc[]


[[contacts]]
== Contacts

Facilities have emergency, operator and service contacts, where the two first are mandatory and service contact optional. Contacts are either general,
maintained by HSL and shared by all operators, or operator specific. Operator specific contacts have
`operatorId` property.

include::{generated}/all-contacts-example/http-request.adoc[]
include::{generated}/all-contacts-example/http-response.adoc[]

Contacts can be searched with optional `ids` [0..n] and `operatorId` [0..1] parameters:

include::{generated}/find-contacts-by-ids-example/http-request.adoc[]
include::{generated}/find-contacts-by-operator-id-example/http-request.adoc[]

Contact details can fetched by id:

include::{generated}/contact-details-example/http-request.adoc[]
include::{generated}/contact-details-example/http-response.adoc[]

=== Summary of Contacts Model

include::{generated}/contact-details-example/response-fields.adoc[]


[[facilities]]
== Facilities

[[facility-search]]
=== Search Facilities

Facility collection resource allows filtering returned items by status, ids and location.
These parameters can be mixed and matched to suite your use-case.

==== By Status

Use multi-valued `statuses` parameter to filter by status, e.g. only facilities that are
IN_OPERATION or have some EXCEPTIONAL_SITUATION:

include::{generated}/find-facilities-by-statuses-example/http-request.adoc[]

For status details, e.g. information about EXCEPTIONAL_SITUATION, see <<facility-details,`statusDescription`>>.

==== By Ids

Sometimes you know IDs of multiple facilities and want to get their basic information as
quickly as possible. This is the case with hubs, that only know the `facilityIds` of
related facilities. Multi-valued `ids` -parameter is made for just this:

include::{generated}/find-facilities-by-ids-example/http-request.adoc[]

[[spatial-search]]
==== Spatial Search

Facilities have a `location` that is a Polygon in WGS84 (or EPSG:4326) projection.
Facilities can be searched using http://en.wikipedia.org/wiki/Well-known_text[WKT]-formatted
`geometry` query parameter.
Supported geometry types are

* Point
* LineString
* Polygon
* MultiPoint
* MultiLineString
* MultiPolygon

You may test spatial searches with link:/#/search-demo[Search Demo].

===== Within Shape

If only `geometry` is specified, facilities whose location overlaps with it are returned.

include::{generated}/find-facilities-by-geometry-example/http-request.adoc[]

===== Within Max Distance

If `maxDistance` (double) is specified along side `geometry` then facilities whose location
is within given max distance (meters) are returned.

include::{generated}/find-facilities-by-geometry-max-distance-example/http-request.adoc[]

==== Summary of Matching Facilities

An existence of a special parameter named `summary` transforms results into a summary of matched
facilities. This summary consists of `facilityCount` and sum of capacity by type.

include::{generated}/find-facilities-summary-example/http-request.adoc[]
include::{generated}/find-facilities-summary-example/http-response.adoc[]


[[facility-details]]
=== Facility Details

include::{generated}/facility-example/http-request.adoc[]

include::{generated}/facility-example/http-response.adoc[]

[[status]]
==== Status

The status of a facility indicates whether the facility is operating normally or not.

`IN_OPERATION`::
Facility is operating normally and is open according to the regular opening hours.
See the facility's `openingHours` field to find out whether the facility is open right now.
`INACTIVE`::
Facility has been decommissioned or has not yet been opened.
`TEMPORARILY_CLOSED`::
Facility is currently closed, ignoring the opening hours, but will be opened again in near future.
`EXCEPTIONAL_SITUATION`::
There is something exceptional happening, but the facility is still open.
For example one gate or floor is closed, but the rest of the facility is working normally.
See the `statusDescription` field for an explanation of what is happening.

[[capacity]]
==== Capacity

Facilities have built capacity for different types of vehicles.
This capacity may be divided for different purposes (usage).
As the time of writing this document, we have identified three different usage types

`PARK_AND_RIDE`::
This kind of parking slots are meant for commuters that continue to their work place by public transportation.
`HSL_TRAVEL_CARD`::
As above, but valid HSL Travel Card is required to get in.
`COMMERCIAL`::
Normal parking facility without restrictions for purpose of use.

[[pricing]]
==== Pricing

Park and Ride facility model supports basic pricing use cases: by `capacityType`, `usage`, `dayType` and `time` (of day).
There may be limitations to `maxCapacity` available for different usage types when comparing to builtCapacity.
There are no overlapping pricing rows and full opening hours are accounted.
Time is an interval of `hh[:mm]` - hour of day (00-24) and optional minute (00-59).
Actual prices are described as localized text, while null price means that parking is free-of-charge.
Additional pricing details may be found following `paymentInfo.url` (localized) link or as text
from `paymentInfo.detail` field.

As there are many free 24 hours a day, 7 days a week parking facilities near public transportation hubs,
there exists a short cut for that: `pricingMethod` with value `PARK_AND_RIDE_247_FREE`.
However, even in this case all implied pricing rows are accounted for all specified `buildCapacity` types.

==== Unavailable Capacity

Temporarily unavailable capacity is defined in `unavailableCapacities` with at most one entry
for capacityType-usage pair. This should be discounted from `pricing[].maxCapacity`.

NOTE: This information is mainly useful for facilities from which there is
no dynamic utilization information available. Otherwise one should refer to utilization and prediction.

[[utilization]]
=== Utilization

If available, the latest known number of available parking places is reported.

include::{generated}/utilization-example/http-request.adoc[]
include::{generated}/utilization-example/http-response.adoc[]
include::{generated}/utilization-example/response-fields.adoc[]

A single facility may contain many different capacity type and usage combinations.
This API will show all distinct combinations which have utilization data
and which are listed in <<facility-details,the facility's pricing field>>.

include::{generated}/utilization-many-example/http-request.adoc[]
include::{generated}/utilization-many-example/http-response.adoc[]

[[utilization-update]]
==== Updating

<<authentication,Authenticated>> operators may update the utilization for their facilities.

In case of network failure, the updater should keep a copy of the utilization snapshots and retry sending them later.
It is possible to batch insert multiple utilization snapshots with a single request per facility;
just have multiple objects inside the request payload's top-level JSON array.

The API allows inputting also old utilization data, but to avoid <<utilization-prediction,prediction>> hiccups,
the utilization _should_ be inputted in timestamp order, oldest first.
Utilizations with future timestamps are not allowed.
The timestamps must be in ISO 8601 date time format, with timezone.
The `Authorization` and `Content-Type` headers are required.
The response reports the latest utilization, same as with a GET request.

include::{generated}/utilization-update-example/curl-request.adoc[]
include::{generated}/utilization-update-example/http-request.adoc[]
include::{generated}/utilization-update-example/http-response.adoc[]

Example of updating the utilization of multiple usage types within the same facility:

include::{generated}/utilization-update-many-example/http-request.adoc[]

[[utilization-prediction]]
==== Prediction

Utilization predictions are available for all facilities which have enough utilization data history.
The predictions are updated at regular intervals (e.g. 5 min) and they are available for up to 24 hours into the future.
It is possible to query predictions using relative time (`after` parameter in `hh:mm` format or in minutes)
or absolute time (`at` parameter in ISO 8601 date time format).

include::{generated}/prediction-relative-example-hhmm/http-request.adoc[]
include::{generated}/prediction-relative-example-hhmm/http-response.adoc[]

include::{generated}/prediction-relative-example-minutes/http-request.adoc[]
include::{generated}/prediction-relative-example-minutes/http-response.adoc[]

include::{generated}/prediction-absolute-example/http-request.adoc[]
include::{generated}/prediction-absolute-example/http-response.adoc[]

==== Facility GeoJSON Example

GeoJSON of a single facility contains only basic information of a facility, not full details:

include::{generated}/facility-geojson-example/curl-request.adoc[]
include::{generated}/facility-geojson-example/http-response.adoc[]

GeoJSON FeatureCollection of facilities:

include::{generated}/geojson-suffix-example/curl-request.adoc[]
include::{generated}/geojson-suffix-example/http-response.adoc[]

==== Summary of Facility Model

include::{generated}/facility-example/response-fields.adoc[]


[[hubs]]
== Hubs

Public transportation hubs are places where trains, buses, cars and bicycles converge.
From a hub one may continue to all places reachable via public transportation.
Hubs are named and defined as a location with optional address as well as a list
of `facilityIds` that refer to parking facilities that are easily reachable from the hub.
Basic information of those facilities may be searched from the <<facilities,`facilities`>> resource using the `ids` parameter,
or by querying for details of each facility separately.

include::{generated}/all-hubs-example/http-request.adoc[]
include::{generated}/all-hubs-example/http-response.adoc[]

[[hub-search]]
=== Search Hubs

Hubs may be searched by (hub) `ids`, `facilityIds` and `geometry` within optional `maxDistance`.
<<spatial-search>> of hubs works similarly to facilities.

include::{generated}/find-hubs-by-ids-example/http-request.adoc[]
include::{generated}/find-hubs-by-facility-ids-example/http-request.adoc[]
include::{generated}/find-hubs-by-geometry-example/http-request.adoc[]
include::{generated}/find-hubs-by-geometry-max-distance-example/http-request.adoc[]

[[hub-details]]
=== Hub Details

At the time of writing this document there is no structural difference between individual hub resource
(`hubs/123`) and an item in `hubs` collection resource.

include::{generated}/hub-details-example/http-request.adoc[]
include::{generated}/hub-details-example/http-response.adoc[]

==== Hub GeoJSON Example

GeoJSON of a single hub:

include::{generated}/hub-geojson-example/curl-request.adoc[]
include::{generated}/hub-geojson-example/http-response.adoc[]

GeoJSON FeatureCollection of hubs:

include::{generated}/geojson-header-example/curl-request.adoc[]
include::{generated}/geojson-header-example/http-response.adoc[]

==== Summary of Hub Model

include::{generated}/hub-details-example/response-fields.adoc[]

[[hub-prediction]]
=== Prediction

Utilization predictions are available for all hubs which have facilities with enough utilization data history. The hubs'
predictions are simply sums of the related facilities' predictions.

include::{generated}/hub-prediction-relative-example-hhmm/http-request.adoc[]
include::{generated}/hub-prediction-relative-example-hhmm/http-response.adoc[]

include::{generated}/hub-prediction-relative-example-minutes/http-request.adoc[]
include::{generated}/hub-prediction-relative-example-minutes/http-response.adoc[]

include::{generated}/hub-prediction-absolute-example/http-request.adoc[]
include::{generated}/hub-prediction-absolute-example/http-response.adoc[]


[[use-cases]]
== Use-Case Examples

=== Park and Ride With a Navigator

A navigation app may search for hubs within `maxDistance` of 1000 m of the selected route.
A route is defined as a `LineString` `geometry` which is in essence just a list of coorinates.
From the result a list of recommended facilities may be extracted and then
prediction of spaces available at the estimated arrival time.


&copy; Copyright HSL