= HSL Liipi Documentation
:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs


[[overview]]
= Overview

HSL Park and Ride application contains information about parking facilities near public transportation hubs.
Data is provided free-or-charge with XXX License.

API follows REST conventions (roughly). Resources are divided into collection and item URLs.
Collection resources typically accept GET-parameters for filtering, paging and sorting items.
Reading data uses GET-method and doesn't require authorization - except for user management.
Restricted modifications use either POST on collection-URL for creating new items and PUT
on item URL for updates.

DELETE is not directly supported (currently) but the goal is achieved using e.g. a status field.
However, if sometime in the future we need to delete something for reason or another,
*please prepare for 404 on a resource that has previously returned a result*.

Somewhat contrary to strict REST ideology we provide all dependent (deep) information directly from
item URLs. You need not get basic relations using nested calls.
Shared resources are referenced using IDs (not URIs), and until HATEOAS-type links are implemented
one needs to know and construct URIs using templates in order get details of such shared resources
(e.g. operator or contacts).
For most cases there exists an ID-based filtering parameter (`ids`) for collection URLs
that allow getting basic information of all referred resources with single request.

== Changes to the API

We aim to develop the API in a backwards compatible manner, i.e. features are only added while
maintaining old semantics. However, we appreciate your feedback and will take it into account
in future development. In the end, this may lead to a need to refactor the APIs.
Unless such a breaking change is due to some critical security related issue, we will give you
a warning about it well in advance.
_Please register yourself and your app to a (TODO!) mailing list
in order to receive announcements of comming changes._

== Development

Park and Ride application developed as an Open Source project in GitHub:
https://github.com/HSLdevcom/parkandrideAPI.

Please, report bugs and feature requests as GitHub issues.

== Examples

Most API-features are used by our own maintenance UI (http://p.hsl.fi) and
it's source code is a good source for real life examples.
See also https://github.com/HSLdevcom/parkandrideAPI/tree/master/application/src/main/frontend/src[GitHub].

== License

Source code is licensed under AGPL and EUPL licenses. For details, see
https://github.com/HSLdevcom/parkandrideAPI#license.

[[authentication]]
= Authentication

Mutable operations require authentication using the `Authorization` header as shown in the following example.
The value is the string `Bearer` followed by the API user's token.

include::{generated}/authentication-example/http-request.adoc[]

NOTE: Authentication is *not* needed for read-only (GET) methods.


[[supported-formats]]
= Supported Formats

Both JSON and http://geojson.org[GeoJSON] (Feature/FeatureCollection) are supported for facilities and hubs.
In JSON format locations are provided using GeoJSON Geometries (Point or Polygon).
GeoJSON's feature centric view contains only basic metadata of given entity.

Required format is specified either with `.json` or `.geojson` suffix or by using `Accept` header with
`application/json` or `application/vnd.geo+json` value.

include::{generated}/json-suffix-example/curl-request.adoc[]

include::{generated}/geojson-suffix-example/curl-request.adoc[]

include::{generated}/json-header-example/curl-request.adoc[]

include::{generated}/geojson-header-example/curl-request.adoc[]

If no suffix or `Accept` header is given, JSON is used by default.

include::{generated}/json-default-example/curl-request.adoc[]


[[searching]]
= General Search Features

While simple listings (e.g. enums) may return arrays of values directly, searches return results
that are wrapped within an object. This result object has boolean field `hasMore` that indicates whether
or not there's more result rows available:

[source,json]
----
{
  "results": [...]
  "hasMore": false
}
----

Limiting result size is done via `limit` and `offset` int-parameters.
Limit defines the maximum number of items to be returned and offset the zero-based index of
the first row to be returned.

Ordering of result items is done via `sort.by` and `sort.dir` parameters.
Allowed values of `sort.by` is resource dependent but typically
at least `name.fi`, `name.sv` and `name.en` are supported.
Direction is given as `ASC` or `DESC`.

TODO: CURL-EXAMPLE!


[[localization]]
= Localization

Park and Ride data is localized in Finnish, Swedish and English.
Localized fields are represented as objects with `fi`, `sv` and `en` fields:

[source,json]
----
{
  "name": {
    "fi": "Nimi",
    "sv": "Namn",
    "en": "Name"
  }
}
----

Optional localized fields are either `null` or localized for all supported languages.
For example missing (optional) info:

[source,json]
----
{
  "info": null
}
----


[[enumerations]]
= Enumerations

Park and Ride utilizes enumerated values for much of it's metadata. Current value-sets are available via REST.

CapacityType defines different kind of parking slot types:

include::{generated}/enumeration-capacity-types-example/http-request.adoc[]
include::{generated}/enumeration-capacity-types-example/http-response.adoc[]

DayType, a rough categorization of day types with different opening hours and/or pricing:

include::{generated}/enumeration-day-types-example/http-request.adoc[]
include::{generated}/enumeration-day-types-example/http-response.adoc[]

Services provided by parking facility:

include::{generated}/enumeration-services-example/http-request.adoc[]
include::{generated}/enumeration-services-example/http-response.adoc[]

PaymentMethods accepted by facility:

include::{generated}/enumeration-payment-methods-example/http-request.adoc[]
include::{generated}/enumeration-payment-methods-example/http-response.adoc[]

FacilityStatuses:

include::{generated}/enumeration-facility-statuses-example/http-request.adoc[]
include::{generated}/enumeration-facility-statuses-example/http-response.adoc[]

PricingMethod is a shortcut for maintaining actual facility pricing information:

include::{generated}/enumeration-pricing-methods-example/http-request.adoc[]
include::{generated}/enumeration-pricing-methods-example/http-response.adoc[]


[[operators]]
= Operators

All facilities are operated by an operator. Operator can be listed with:

TODO: EXAMPLE!

Details (i.e. localized name) of an operator can be fetched with:

TODO: EXAMPLE!


[[contacts]]
= Contacts

Facilities have emergency, operator and (optional) service contacts. Contacts are either general,
maintained by HSL and shared by all operators, or operator specific. Operator specific contacts have
`operatorId` property.

Contacts can be searched with optional `ids` [0..n] and `operatorId` [0..1] parameters:

TODO: EXAMPLE!

Contact details can fetched by id:

TODO: EXAMPLE!



[[facilities]]
= Facilities

include::{generated}/facility-example/response-fields.adoc[]

include::{generated}/facility-example/http-request.adoc[]

include::{generated}/facility-example/http-response.adoc[]


[[facility-search]]
== Search Facilities



=== By Status
=== By Ids
=== Spatial
==== Within Shape
==== Within Max Distance
=== Summary

[[facility-details]]
== Facility Details
=== Pricing
=== Minimal Information
=== Full Information

[[utilization]]
= Utilization
== Update
== Prediction


[[hubs]]
= Hubs
== Overview
== Search Hubs
== Hub Details
