FROM node:10 AS builder

# tools
RUN apt-get update && \
    apt-get install -y zopfli && \
    rm -rf /var/lib/apt/lists/*

# some bower components expect that bower is installed
RUN npm install -g bower

# working directory
RUN mkdir -p /project && \
    chown node /project
WORKDIR /project
USER node

# cache node_modules
COPY --chown=node package.json yarn.lock /project/
RUN yarn install --frozen-lockfile --non-interactive --no-progress && \
    yarn cache clean && \
    bower cache clean
LABEL cache-this-layer=liipi-web-builder-cache

# do the build
COPY --chown=node *.* /project/
COPY --chown=node karma /project/karma/
COPY --chown=node src /project/src/
RUN yarn run build

# offline compress static resources
RUN find /project/bin/static -type f -regextype posix-extended \
        -iregex '.*\.(html?|js|css|svg|otf|eot|ttf|woff|txt|json)' \
        -exec zopfli '{}' \;

# ------------------------------------------------------------

FROM nginx:1.15-alpine

COPY docker/nginx-default.conf.template /etc/nginx/conf.d/default.conf.template

COPY docker/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

COPY --from=builder /project/bin/static /usr/share/nginx/html
