FROM node:10 AS builder

# some bower components expect that bower is installed
RUN npm install -g bower

# working directory
RUN mkdir -p /project && \
    chown node /project
WORKDIR /project
USER node

# cache node_modules
COPY --chown=node package.json yarn.lock /project/
RUN yarn install --frozen-lockfile --non-interactive --no-progress && \
    yarn cache clean && \
    bower cache clean
LABEL cache-this-layer=liipi-web-builder-cache

# do the build
COPY --chown=node *.* /project/
COPY --chown=node karma /project/karma/
COPY --chown=node src /project/src/
RUN yarn run build

# ------------------------------------------------------------

FROM nginx:1.15-alpine

COPY docker/nginx-default.conf /etc/nginx/conf.d/default.conf

COPY docker/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

COPY --from=builder /project/bin/static /usr/share/nginx/html
